### ISSUE TITLE
Tags/Langs

### ISSUE THREAD

**Issue by webquali** [vidinoti/angular-pixlive#2]
Hi I have created content with lang tag but when send request for specific lang for example thi
PxlRemoteController.synchronize(['test']).then(function(contexts) {
        console.log('Syncronization OK: ');
        console.log(contexts);
    }, function(reason) {
        $ionicPopup.alert({
            title: 'PixLive Synchronization Error',
            template: reason
        });
    }, function(progress) {
        console.log('Synchronization progress: '+progress);
    });

All time I have in result all content items not tag specified.
Where problem?

**Comment by jleuleu** [comment]
Hello,
You need to enable the tag support in PixLive Maker.

1. Connect to PixLive Maker (https://armanager.vidinoti.com)
2. Go to PixLive SDK > My Applications
3. Edit the configuration of your application and ensure that the checkbox "Use tag management system" is checked.

If you don't do that, the synchronization per tag has no effect (i.e. all contents are synchronized)
