### ISSUE TITLE
Problem with layuout

### ISSUE THREAD

**Issue by webquali** [vidinoti/angular-pixlive#3]
Hi,

I have this layout, my problem I can't click to button "Home"

`<ion-view style="background-color: transparent !important;" hide-nav-bar="true"> <pxl-view pxl-context-enter="contextEnter" > <button ng-click="closeArViewButton()" class="button button-balanced text-center">HOME</button> </pxl-view> </ion-view>`

Can you help me understand why?

**Comment by jleuleu** [comment]
Hello,
Please see https://github.com/vidinoti/cordova-plugin-PixLive/issues/4
The pxl-view intercepts the touch events, you need to disable the touch event on the arView with `arView.disableTouch()`
For example, this is automatically handled for the modals (https://github.com/vidinoti/angular-pixlive/blob/master/js/PixLive.js#L108)

Johan
